# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   http://docs.travis-ci.com/user/languages/r/

language: R
sudo: required
warnings_are_errors: true

r_github_packages:
  - hadley/httr
  - jeroenooms/jsonlite
  - jeroenooms/curl

before_install: 
  - Rscript -e "install.packages('roxygen2', repos='http://cran.us.r-project.org'); library(roxygen2); roxygen2::roxygenize(package.dir='.', roclets=c('rd', 'collate', 'namespace'))"
  
after_success:  
  - Rscript -e 'source("R/tests/testRSocrata.R"); runAllTestsCI()'

notifications:
  email:
    on_success: change
    on_failure: change
